apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-high
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    path: security/sealed-secrets
    repoURL: https://github.com/basdemir/infra-kube
    targetRevision: HEAD
  destination:
    server: https://10.151.254.18:6443
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true

