apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
#- ingress.yaml
patches:
- path: redis_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-redis
patchesStrategicMerge:
- server.yaml
- repo-server.yaml
images:
- name: quay.io/argoproj/argocd
  newName: dockerepo.hvl.io/tools/quay.io/argoproj/argocd
- name: ghcr.io/dexidp/dex
  newName: dockerepo.hvl.io/tools/ghcr.io/dexidp/dex
- name: redis
  newName: dockerepo.hvl.io/tools/redis
namespace: argocd
