bases:
  - ../../base

images:
- name: quay.io/argoproj/argocd
  newName: dockerepo.hvl.io/tools/quay.io/argoproj/argocd
- name: ghcr.io/dexidp/dex
- newName: dockerepo.hvl.io/tools/ghcr.io/dexidp/dex
- name: redis:6.2.4-alpine
- newName: dockerepo.hvl.io/tools/redis:6.2.4-alpine